### ISSUE TITLE
Introduce "offline" support

### ISSUE THREAD

**Issue by raulriera** [Topener/XHR#11]
Just as the module passes the "cache" info, it should pass an "offline" (or something) back when there is no connectivity (or very poor?) on the device

**Comment by sindresorhus** [comment]
:+1:

**Comment by mikedias** [comment]
:+1:

**Comment by nuno** [comment]
:+1:   man I love this lib.

**Comment by arifje** [comment]
yeah! :-]

**Comment by raulriera** [comment]
Thanks guys! ❤️ I am looking for maintainers if anyone want to tackle these tickets

**Comment by Topener** [comment]
@raulriera could you explain what exactly you would expect? I will try to set it up ;)

**Comment by raulriera** [comment]
I was thinking of the library to automatically return any cached responses when the connection is offline. This would have be to settable and with a status of "offline" or something I guess. at the time I was doing that manually every time I was firing a request @Topener

**Comment by Topener** [comment]
As of right now it automatically returns a cached response if there is cache. Should this mean it will cache when there is no TTL either, but only use it for offline purposes?

**Comment by raulriera** [comment]
No, that is fine. before it returned an error if I remember correctly. It's been a while 😅

**Comment by Topener** [comment]
Ah... yeah  a 3 year old ticket. Lets close it then ;)
