### ISSUE TITLE
location of xhr.js in app structure

### ISSUE THREAD

**Issue by stereoket** [Topener/XHR#12]
Great library, I am wondering if the actual xhr.js file should be located in the lib folder with the taffydb file.

Having it in the root, is not how I would structure an app, but thats just may approach. Just wonder what you're opinions are on that.

**Comment by raulriera** [comment]
I keep it in the lib folder as well :) just thought having it "visible" here at first glance was better

**Comment by stereoket** [comment]
I woud say if it was where it will be used in the app, then people can download and "install" it rather than opening files and changing paths, the README could cover the features... OR perhaps use javadoc blocks in the code and export documentation for it (I might be willing to do that)!

**Comment by raulriera** [comment]
Im open to the documentation thing :) about changing paths, you shouldn't need to, XHR calls /lib/taffy (which will work no matter where XHR is located. Are you having problems using xhr out of the box if you drop it on the lib folder?

**Comment by stereoket** [comment]
I don't think so can't remember now. But I think we can do some documentation stuff..

**Comment by chrisribe** [comment]
Hello,

Great module thanks !!
I have a code structure question, which is kinda related.

When using the module should I re-declare the require for each module that uses XHR ?
Or should I declare it globaly in app.js ?

var XHR = require("/common/xhr");
var _xhr = new XHR();

Thanks
Chris

**Comment by raulriera** [comment]
Hi,

It depends on how you code your app, you need to include it in every single
"context" you declare on your app.

Hope that helped

Raul
@raulriera
