### ISSUE TITLE
Re-package

### ISSUE THREAD

**Issue by ricardoalcocer** [Topener/XHR#17]
Wanted to suggest you package it like this: https://github.com/ricardoalcocer/tiactionbarhelper/tree/master/Package/commonjs/com.alcoapps.actionbarhelper/1.0.0

so it can be added via tiapp.xml regardles of Ti Classic or Alloy.  I'm trying to get @fokkezb to add support for commonjs modules to the gittio CLI.

R

**Comment by raulriera** [comment]
Thanks man, although seems a bit overkill :(
