### ISSUE TITLE
keeping an data in cache forever untill app is removed.

### ISSUE THREAD

**Issue by dpz3579** [Topener/XHR#20]
hi as your 'ttl' specifies that the time duration for which data must be cached.

my question is can you keep a document in cache as in web you have if cache time is set as -1, it is forever in the browser cache until user removes it.

can you please look into it, else if possible please guide me how can one achieve it.

thanks a lot...

**Comment by raulriera** [comment]
Why not simply create a large timeout? what is the difference between 3 years and forever?

**Comment by dpz3579** [comment]
ya i'm using that only..

thanks for the reply.. :)
