### ISSUE TITLE
Is there a way of having XHR requests queue?

### ISSUE THREAD

**Issue by mark22** [Topener/XHR#26]
I have an app that may have multiple XHR requests firing at the same time, which I can see having conflicts.  Is there a way of ordering all the xhr requests into a queue?

For example

```
xhr.ADD("http://freegeoip.net/json/", onSuccessCallback, onErrorCallback, options);
xhr.ADD("http://freegeoip.net/json2/", onSuccessCallback, onErrorCallback, options);
xhr.ADD("http://freegeoip.net/json3", onSuccessCallback, onErrorCallback, options);
```

Will try to run `http://freegeoip.net/json/` first, and when that is complete, move on to `http://freegeoip.net/json2/` then `http://freegeoip.net/json3/`

?

**Comment by Topener** [comment]
There is no support for queueing or promises. But you can easily use callbacks for that or write a queue wrapper for xhr.js. The queue wrapper could also be a great open source project next to xhrjs or a secondary js file as a plugin
