### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by HazemKhaled** [Topener/XHR#28]
Hey,

As you know Titanium allows upload files by put files in xhr.send() for example
```javascript
var xhr = Ti.Network.createHTTPClient();
xhr.open('POST', 'http://about.me/hazemkhaled/upload');
xhr.send({
    db: Ti.Filesystem.getFile('/bla/bla/bla/file.zip')
});
```

While this not working with our module sure when you parseJSON = true cos this line
https://github.com/raulriera/XHR/blob/master/xhr.js#L94
```javascript
xhr.send(extraParams.parseJSON ? JSON.stringify(data) : data);
```

And force contentType is application/json
https://github.com/raulriera/XHR/blob/master/xhr.js#L264
```javascript
extraParams.contentType = extraParams.contentType || "application/json";
```

Solution:
1. Check `data` before damage it into `JSON.stringify`, or maybe don't to stringify it at all
2. Remove line [264](https://github.com/raulriera/XHR/blob/master/xhr.js#L264)

**Comment by Topener** [comment]
Thanks. Though removing line 264 will remove backward compatibility which we shouldn't do. The checking I agree with, but when uploading a file the content type should be set properly in that case. 

Could you create a PR for the checking?

**Comment by HazemKhaled** [comment]
Sure

**Comment by Topener** [comment]
Hi,

looking back at this ticket from 1,5 years ago. I think just passing `extraParams` with the specific endpoint should fix it for you. As it can be overridden per endpoint.

```
extraParams: {parseJSON: false}
```
