### ISSUE TITLE
Module not found, package error?

### ISSUE THREAD

**Issue by R4mpancy** [Topener/XHR#31]
Wanted to give this module a try but haven't been able to get it to install properly. Pretty familiar with installing modules, so I don't think I'm doing anything wrong.

I have both versions installed globally in ~/Library/Application Support/Titanium/modules/commonjs/xhr/<version>

When trying to build & run my app with xhr v3.0.0 I get an error:
`[DEBUG] :  Looking for Titanium module id=xhr version=3.0.0 platform=commonjs deploy-type=development
[INFO] :   Found Titanium module id=xhr version=3.0.0 platform=commonjs deploy-type=development path=/Users/macdev/Library/Application Support/Titanium/modules/commonjs/xhr/3.0.0
2018-04-30T14:34:15.137Z | ERROR  | An uncaught exception was thrown!
Cannot find module '/Users/macdev/Library/Application Support/Titanium/modules/commonjs/xhr/3.0.0'
2018-04-30T14:34:15.138Z | ERROR  | Cannot find module '/Users/macdev/Library/Application Support/Titanium/modules/commonjs/xhr/3.0.0'
2018-04-30T14:34:15.138Z | TRACE  | Error: Cannot find module '/Users/macdev/Library/Application Support/Titanium/modules/commonjs/xhr/3.0.0'`

When building and running with xhr v2.1.0 the module gets found correctly and builds:
`[DEBUG] :  Detected commonjs module: xhr 2.1.0 @ /Users/macdev/Library/Application Support/Titanium/modules/commonjs/xhr/2.1.0
[DEBUG] :  Detected commonjs module: ti.xhr 3.0.0 @ /Users/macdev/Library/Application Support/Titanium/modules/commonjs/xhr/3.0.0`

However on Android when the require gets ran in alloy.js like in the example it throws a module not found error:
`[ERROR] :  Error: Requested module not found: ti.xhr
[ERROR] :  File: app.js
[ERROR] :  Line: undefined
[ERROR] :  SourceId: undefined
[ERROR] :  Backtrace:
[ERROR] :  undefined`

On iOS though, it fails to build with an error;
`[ERROR] :  There is a project resource "xhr.js" that conflicts with a native iOS module
[ERROR] :  Please rename the file, then rebuild`

Should also note that when I took a peek into the module's files I noticed the manifest files were Unix executables and not text files.
I have not tested installing the modules locally to the project yet.

**Comment by Topener** [comment]
Thanks! There indeed was a packaging error.. folder should've been named ti.xhr instead. I've uploaded a new build. Can you try?

**Comment by R4mpancy** [comment]
I'm at college right now and unable to remote into my desktop at work. I'll test again first thing in the morning 9:30 EST

**Comment by Topener** [comment]
Great! Keep me posted

**Comment by R4mpancy** [comment]
Pulled down the updated files after your last commit. I was able to get the module installed correctly and test with it inside an app. However, that was with v3.0.0, the 2.1.0 version still was lacking the "ti." prefix after installing that version of the module.

**Comment by Topener** [comment]
great! Yeah from 2.x to 3.x there was a small rename & structure change. The 2.x version will remain the same as it was.

So that one has to be included as just `xhr`
