### ISSUE TITLE
HTTP Headers Support

### ISSUE THREAD

**Issue by mardo** [Topener/XHR#9]
How do i set an HTTP Header to the request?

**Comment by raulriera** [comment]
Content types? refer to the xhr.js for some info on the params.contentType property

**Comment by mardo** [comment]
Hello Raul,
I'm talking about setting a custom HTTP Header, let's say "X-Redmine-API-Key" to make a Redmine REST API for example.

**Comment by raulriera** [comment]
Hello,

I see, there is no direct support. But you can easily hack the module to accept it since at the end is just a simple HTTPClient from Titanium which accepts a setRequestHeader('header', value);

I would suggest another "params" to the params object and append it there if one is sent
